### ISSUE TITLE
Supporting UserContext in bug reports

### ISSUE THREAD

**Issue by ksdme** [futureware-tech/flutter_sentry#14]
It would be nice to have UserContext as part of bug reports. This could probably be achieved by passing an async user context generator function to `FlutterSentry.wrap`.

I am open to making a PR adding this support. Please let me know if I should go ahead.

**Comment by dotdoom** [comment]
Definitely on our radar. This is arriving soon!

**Comment by dotdoom** [comment]
Carrying more information over from internal planning doc --

We should have a method on `FlutterSentry.instance` to set user ID / UserContext, which will then be propagated to platform code as well (to make sure native code exceptions also contain correct UserContext).

**Comment by dotdoom** [comment]
This is not yet done: while `userContext` is now supported on the Flutter side, it still does not propagate to platform code.

I.e. fatal crashes on the platform side will not preserve the context.

**Comment by fzyzcjy** [comment]
Hi is there any updates (after nearly a year?) Thanks!

**Comment by dotdoom** [comment]
Takes a while to get things done reliably on iOS -- I'll try to make it work before the end of the year.  And hey, there has been an update in March :-)

**Comment by fzyzcjy** [comment]
Sounds great (though a bit slow). I am interested to help, so how could I help? IMHO it is just as simple as writing something similar to `setNativePlatformEnvironment`

**Comment by fzyzcjy** [comment]
@dotdoom PR created

**Comment by dotdoom** [comment]
Fixed in #51
