### ISSUE TITLE
Support Release Health tracking

### ISSUE THREAD

**Issue by SarcasticNoodle** [futureware-tech/flutter_sentry#27]
**The problem**
The version of the Sentry Android Sdk is currently at 2.0.0 and this version does not support Release Health monitoring

**Describe the solution you'd like**
Upgrade the version to 2.1.0 and add documentation how to add this feature, as described here: https://docs.sentry.io/platforms/android/#release-health

**Comment by dotdoom** [comment]
This has been fixed and released 🎉

**Comment by kuhnroyal** [comment]
Can this also be supported for iOS? https://docs.sentry.io/platforms/cocoa/?platform=swift#release-health
Maybe with optional values `SentryEnableAutoSessionTracking` and `SentrySessionTrackingIntervalMillis` from `info.plist`.

**Comment by dotdoom** [comment]
Good point, I didn't see it in the docs before (or was it just released?).  Reopening for tracking purposes.

**Comment by dotdoom** [comment]
Implemented in #40 , released in 0.4.4.
