### ISSUE TITLE
I would like to log important warnings to sentry with the stacktrace like an exception 

### ISSUE THREAD

**Issue by ride4sun** [futureware-tech/flutter_sentry#31]
I would like to log important warnings to sentry with the stack trace like an exception but I don't want to interrupt the program as an exception does. Could we add something like that to this lib? 

I also filed a stackoverflow request:
https://stackoverflow.com/questions/62603708/how-can-i-log-a-warning-to-sentry-with-flutter?noredirect=1#comment110711254_62603708

**Comment by dotdoom** [comment]
Hi there,

Sorry for slow response.

You have two options here with Sentry:

1. Log the warning and have bundled together with subsequent Error event, if any. `flutter_sentry` does this for you automatically: anything logged via `print()` or `debugPrint()` is already logged as a breadcrumb.

2. Send the warning as a non-fatal event to Sentry. This can be done via [`captureException`](https://github.com/dasfoo/flutter_sentry/blob/6c9201a4f3ee3fb54d3e764d86424a4d202619dc/lib/flutter_sentry.dart#L167) method. For example:

```dart
FlutterSentry.wrap(() {
  // ...
  // This will report a non-fatal event to Sentry, including current stack trace, device and application info.
  FlutterSentry.instance.captureException(exception: Exception('Things went wrong'));
  // This will report a non-fatal event to Sentry, including current stack trace, device and application info.
  FlutterSentry.instance.captureException(
      exception: Exception('Things went wrong'),
      extra: {
          // Free form values to attach to the event.
          'application state': 'unstable',
      },
  );

});
```

If this helps, I'll comb it a little and include in the documentation.

**Comment by dotdoom** [comment]
Documented in #54
