### ISSUE TITLE
I don't want to see your logging in my app.

### ISSUE THREAD

**Issue by robertflesch** [futureware-tech/flutter_sentry#64]
Sentry creates TONS of logging info.
This just creates noise in my app which is not welcome.
I love what sentry does, but I would prefer not seeing YOUR logging unless I turn on verbose mode.
Give me important milesstone, not all the details.
I am using sentry_flutter: ^6.2.0

I/Sentry  ( 8145): Initializing SDK with DSN: '<redacted>'
I/Sentry  ( 8145): GlobalHubMode: 'true'
W/pool-4-thread-1( 8145): type=1400 audit(0.0:1818): avc: denied { read } for name="version" dev="proc" ino=4026532035 scontext=u:r:untrusted_app:s0:c121,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=XXX.XXX
D/Sentry  ( 8145): UncaughtExceptionHandlerIntegration enabled: true
D/Sentry  ( 8145): default UncaughtExceptionHandler class='org.chromium.base.JavaExceptionReporter'
D/Sentry  ( 8145): UncaughtExceptionHandlerIntegration installed.
D/Sentry  ( 8145): ShutdownHookIntegration installed.
D/Sentry  ( 8145): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  ( 8145): NdkIntegration enabled: true
D/Sentry  ( 8145): Started processing cached files from /data/user/0/XXX.XXX/cache/sentry
D/Sentry  ( 8145): Processing dir. /data/user/0XXX.XXX/cache/sentry
D/Sentry  ( 8145): Processing 1 items from cache dir /data/user/0/XXX.XXX/cache/sentry
D/Sentry  ( 8145): File /data/user/0/XXX.XXX/cache/sentry/outbox is not a File.
I/sentry-native( 8145): using database path "/data/data/XXX.XXX/cache/sentry/.sentry-native"
D/Sentry  ( 8145): File /data/user/0/XXX.XXX/cache/sentry/.sentry-native is not a File.
D/Sentry  ( 8145): Processing file: /data/user/0/XXX.XXX/cache/sentry/session.json
D/sentry-native( 8145): starting backend
D/Sentry  ( 8145): File '/data/user/0/XXX.XXX/cache/sentry/session.json' doesn't match extension expected.
D/Sentry  ( 8145): Processing file: /data/user/0/XXX.XXX/cache/sentry/3989cad9-a924-4e8d-a684-c9116df6536f.envelope
D/Sentry  ( 8145): NdkIntegration installed.
D/Sentry  ( 8145): Registering EnvelopeFileObserverIntegration for path: /data/user/0/XXX.XXX/cache/sentry/outbox
D/Sentry  ( 8145): EnvelopeFileObserverIntegration installed.
D/Sentry  ( 8145): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  ( 8145): AnrIntegration enabled: false
D/Sentry  ( 8145): enableSessionTracking enabled: true
D/Sentry  ( 8145): enableAppLifecycleBreadcrumbs enabled: true
D/Sentry  ( 8145): Captured Envelope is already cached
D/Sentry  ( 8145): AppLifecycleIntegration installed.
D/Sentry  ( 8145): ActivityLifecycleIntegration enabled: true
D/Sentry  ( 8145): ActivityLifecycleIntegration installed.
D/Sentry  ( 8145): AppComponentsBreadcrumbsIntegration enabled: true
D/Sentry  ( 8145): AppComponentsBreadcrumbsIntegration installed.
D/Sentry  ( 8145): SystemEventsBreadcrumbsIntegration enabled: true
D/Sentry  ( 8145): SystemEventsBreadcrumbsIntegration installed.
D/Sentry  ( 8145): enableSystemEventsBreadcrumbs enabled: true
D/Sentry  ( 8145): TempSensorBreadcrumbsIntegration installed.
D/Sentry  ( 8145): enableSystemEventBreadcrumbs enabled: true
D/Sentry  ( 8145): Envelope sent successfully.
D/Sentry  ( 8145): Envelope flushed
D/Sentry  ( 8145): Marking envelope submission result: true
W/Sentry  ( 8145): Current session is not ended, we'd need to end it.
D/Sentry  ( 8145): Deleted file /data/user/0/XXX.XXX/cache/sentry/3989cad9-a924-4e8d-a684-c9116df6536f.envelope.
D/Sentry  ( 8145): Finished processing cached files from /data/user/0/XXX.XXX/cache/sentry
D/Sentry  ( 8145): Started processing cached files from /data/user/0/XXX.XXX/cache/sentry/outbox
D/Sentry  ( 8145): Processing dir. /data/user/0/XXX.XXX/cache/sentry/outbox
D/Sentry  ( 8145): Processing 0 items from cache dir /data/user/0/XXX.XXX/cache/sentry/outbox
D/Sentry  ( 8145): Finished processing cached files from /data/user/0/XXX.XXX/cache/sentry/outbox
D/Sentry  ( 8145): Serializing object: {"sid":"b11b6f0f-04be-49b1-8487-2964ea91684f","did":"cca728fa-613d-447e-8d61-6e5d9a59f08d","started":"2022-01-05T18:57:56.383Z","status":"exited","seq":1641409101106,"duration":24.723,"timestamp":"2022-01-05T18:58:21.106Z","attrs":{"release":"news.purified@0.5.28+20","environment":"debug"}}
D/Sentry  ( 8145): Serializing object: {"sid":"0fcaba4c-a91c-416e-b3ad-74bb3a15ad82","did":"cca728fa-613d-447e-8d61-6e5d9a59f08d","init":true,"started":"2022-01-05T18:58:21.021Z","status":"ok","timestamp":"2022-01-05T18:58:21.021Z","attrs":{"release":"news.purified@0.5.28+20","environment":"debug"}}
D/Sentry  ( 8145): Serializing object: {"sid":"0fcaba4c-a91c-416e-b3ad-74bb3a15ad82","did":"cca728fa-613d-447e-8d61-6e5d9a59f08d","init":true,"started":"2022-01-05T18:58:21.021Z","status":"ok","timestamp":"2022-01-05T18:58:21.021Z","attrs":{"release":"news.purified@0.5.28+20","environment":"debug"}}
D/Sentry  ( 8145): Adding Envelope to offline storage: /data/user/0/XXX.XXX/cache/sentry/fe141b4c-a26b-4eef-b087-a433256253cb.envelope
D/Sentry  ( 8145): Envelope sent successfully.
D/Sentry  ( 8145): Discarding envelope from cache: /data/user/0/XXX.XXX/cache/sentry/fe141b4c-a26b-4eef-b087-a433256253cb.envelope
D/Sentry  ( 8145): Envelope flushed

**Comment by dotdoom** [comment]
Hello and thanks for being a nice Flutter community member!

It looks like you are using [`sentry_flutter`](https://pub.dev/packages/sentry_flutter), which is a different package than what we provide here.  Unfortunately, `sentry_flutter` appeared later and we can not do much about the name collision now.  But please do file the report in the corresponding [issue tracker](https://github.com/getsentry/sentry-dart/issues) as we have nothing to do with that package.

A cursory search shows that you may be able to change the behavior with [`diagnosticLevel`](https://pub.dev/documentation/sentry/latest/sentry_io/SentryOptions/diagnosticLevel.html), but don't quote me on that.

Cheers and good luck!

PS as a courtesy I have redacted out the DSN out of your post.  It might not bring much harm to have it around, and it isn't well hidden in the app itself, but a malicious actor can use it to e.g. exhaust your quota.

**Comment by robertflesch** [comment]
Sorry for my confusion, thx for the quick response. 
FYI sentry_flutter has the option.debug = false which removes all logging.
